### ISSUE TITLE
Update grant handling for token-auth.

### ISSUE THREAD

**Issue by paulternate** [SmoothMaverick/datadog-venafi-checks#2]
Current implementation treats the access token like the old API key, and the integration is re-authenticating for every single call and getting a new grant created.

Correct behavior would be to either:

- Revoke grant after call is complete (might not be as performant), OR
- Store both "refresh_token" and "access_token" and use the existing "access_token" for all calls (until it's expired, in which case a new one can be obtained using "refresh_token" and a new pair can then stored for subsequent calls.

**Comment by SmoothMaverick** [comment]
I will take a look at implementing this as soon as I can.

**Comment by SmoothMaverick** [comment]
The Datadog agent doesn't persist any new values between checks. We can add an access token and refresh token to the configuration file, but once a refresh request is made, a new access token and refresh token are returned. 

This means the check will only work as long as the configured access token is valid. The Datadog agent is not able to save the new access and refresh token between checks.

**Comment by SmoothMaverick** [comment]
We can configure the check to read a file containing the access token, and let the user be responsible for refreshing the access token in the configured file.

**Comment by SmoothMaverick** [comment]
We decided to maintain the current implementation and augment the README.md to instruct users to expire the access token after 15 minutes and disable the refresh token.
